# Introduction to EPL Dataset

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataurl = 'https://andybek.com/pandas-soccer'

In [3]:
players = pd.read_csv(dataurl)

In [4]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

In [5]:
players.dtypes.value_counts()

int64      10
object      5
float64     2
dtype: int64

In [6]:
players.head(10)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
6,Olivier Giroud,Arsenal,30,CF,1,22.0,2230,8.5,2.50%,116,2,France,0,4,1,1,0
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
9,Alex Iwobi,Arsenal,21,LW,1,10.0,1812,5.5,1.00%,89,4,Nigeria,0,1,1,1,0

# Review : Indexing with Boolean mask

In [7]:
# Step1: Generate a boolean sequence
# Step2: Use the boolean as a boolean mask

In [8]:
# Q : Find all the players with market_value > 40

In [9]:
players.market_value > 40

0       True
1       True
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [10]:
players[players.market_value > 40]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
97,Diego Costa,Chelsea,28,CF,1,50.0,4454,10.0,3.00%,196,2,Spain,0,4,5,1,0
108,N%27Golo Kante,Chelsea,26,DM,2,50.0,4042,5.0,13.80%,83,2,France,0,3,5,1,1
218,Philippe Coutinho,Liverpool,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
264,Romelu Lukaku,Manchester+United,24,CF,1,50.0,3727,11.5,45.00%,221,2,Belgium,0,2,12,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

# More approaches to boolean mask and comparison operator

In [11]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [12]:
players.position.unique()

array(['LW', 'AM', 'GK', 'RW', 'CB', 'RB', 'CF', 'LB', 'DM', 'RM', 'CM',
       nan, 'SS', 'LM'], dtype=object)

In [13]:
players.position.unique().size

14

In [14]:
# defender : LB, CB, RB

In [15]:
players.position.isin(['LB', 'CB', 'RB'])

0      False
1      False
2      False
3      False
4       True
       ...
460    False
461     True
462     True
463    False
464    False
Name: position, Length: 465, dtype: bool

In [16]:
players[players.position.isin(['LB', 'CB', 'RB'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
17,Gabriel Paulista,Arsenal,26,CB,3,13.0,552,5.0,0.10%,45,3,Brazil,0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0
459,Pablo Zabaleta,West+Ham,32,RB,3,7.0,698,5.0,2.70%,45,3,Argentina,0,5,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0

In [17]:
# Using loc
players.loc[players.position.isin(['LB', 'CB', 'RB'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
17,Gabriel Paulista,Arsenal,26,CB,3,13.0,552,5.0,0.10%,45,3,Brazil,0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0
459,Pablo Zabaleta,West+Ham,32,RB,3,7.0,698,5.0,2.70%,45,3,Argentina,0,5,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0

In [18]:
# between 40 to 50
players.market_value.between(40, 50, inclusive=False)

<ipython-input-18-753e0e399c53>:2: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  players.market_value.between(40, 50, inclusive=False)

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [19]:
players.loc[players.market_value.between(40, 50, inclusive=False)]

<ipython-input-19-730e7b793db4>:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  players.loc[players.market_value.between(40, 50, inclusive=False)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
218,Philippe Coutinho,Liverpool,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0

In [20]:
# Comparison operator
"""
<   --  .lt()
<=  --  .le()
>   --  .gt()
>=  --  .ge()
==  --  .eq()
"""

'\n<   --  .lt()\n<=  --  .le()\n>   --  .gt()\n>=  --  .ge()\n==  --  .eq()\n'

# Binary Operators with Booleans

In [21]:
# Binary OR --> |

In [22]:
# Binary AND --> &

In [23]:
# Binary XOR --> ^

In [24]:
# Two's compliment

# Combining Boolean operators

In [25]:
# Select all left backs

In [26]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [27]:
players.position.head()

0    LW
1    AM
2    GK
3    RW
4    CB
Name: position, dtype: object

In [28]:
players[players.position == 'LB']

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
7,Nacho Monreal,Arsenal,31,LB,3,13.00,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
18,Kieran Gibbs,Arsenal,27,LB,3,10.00,489,5.0,0.50%,45,1,England,0,3,1,1,0
29,Sead Kolasinac,Arsenal,24,LB,3,15.00,618,6.0,6.90%,0,2,Bosnia,1,2,1,1,0
34,Charlie Daniels,Bournemouth,30,LB,3,3.00,185,5.0,19.80%,134,1,England,0,4,2,0,0
54,Brad Smith,Bournemouth,23,LB,3,2.00,297,4.0,3.30%,4,4,Australia,0,2,2,0,0
62,Gaetan Bong,Brighton+and+Hove,29,LB,3,1.50,97,4.5,0.20%,0,4,Cameroon,0,4,3,0,0
65,Markus Suttner,Brighton+and+Hove,30,LB,3,2.00,23,4.5,0.20%,0,2,Austria,0,4,3,0,0
82,Stephen Ward,Burnley,31,LB,3,1.50,152,4.5,2.50%,91,2,Ireland,0,4,4,0,0
99,Marcos Alonso Mendoza,Chelsea,26,LB,3,25.00,3069,7.0,12.40%,177,2,Spain,0,3,5,1,1
112,Kenedy,Chelsea,21,LB,3,7.00,566,5.0,0.10%,3,3,Brazil,0,1,5,1,0
119,Patrick van Aanholt,Crystal+Palace,26,LB,3,9.00,524,5.5,4.20%,98,2,Netherlands,0,3,6,0,0
128,Jeffrey Schlupp,Crystal+Palace,24,LB,3,8.00,385,5.0,0.30%,47,4,Ghana,0,2,6,0,0
134,Pape Souare,Crystal+Palace,27,LB,3,6.00,186,4.5,0.00%,6,4,Senegal,0,3,6,0,0
138,Leighton Baines,Everton,32,LB,3,12.00,491,6.0,10.00%,135,1,England,0,5,7,0,0
168,Chris Lowe,Huddersfield,28,LB,3,1.50,84,4.5,0.70%,0,2,Germany,0,4,8,0,0
175,Scott Malone,Huddersfield,26,LB,3,0.75,81,4.5,0.10%,0,1,England,0,3,8,0,0
196,Christian Fuchs,Leicester+City,31,LB,3,6.00,417,5.0,3.50%,104,2,Austria,0,4,9,0,0
212,Ben Chilwell,Leicester+City,20,LB,3,2.50,288,4.5,0.80%,19,1,England,0,1,9,0,0
236,Alberto Moreno,Liverpool,25,LB,3,10.00,397,4.5,0.30%,8,2,Spain,0,3,10,1,0
251,Aleksandar Kolarov,Manchester+City,31,LB,3,10.00,633,5.5,1.10%,95,2,Serbia,0,4,11,1,0
270,Daley Blind,Manchester+United,27,LB,3,22.00,867,5.5,1.20%,98,2,Netherlands,0,3,12,1,0
281,Luke Shaw,Manchester+United,22,LB,3,20.00,947,5.0,0.40%,45,1,England,0,2,12,1,0
294,Paul Dummett,Newcastle+United,25,LB,3,3.50,177,4.5,1.00%,0,2,Wales,0,3,13,0,0
298,Massadio Haidara,Newcastle+United,24,LB,3,1.50,114,4.0,0.50%,0,2,France,0,2,13,0,0
312,Ryan Bertrand,Southampton,27,LB,3,20.00,578,5.5,11.20%,123,1,England,0,3,14,0,0
328,Matt Targett,Southampton,21,LB,3,3.00,110,4.5,0.20%,12,1,England,0,1,14,0,0
336,Erik Pieters,Stoke+City,28,LB,3,7.00,134,5.0,1.30%,103,2,Netherlands,0,4,15,0,0
354,Josh Tymon,Stoke+City,18,LB,3,1.00,120,4.5,0.10%,9,1,England,0,1,15,0,0
363,Martin Olsson,Swansea,29,LB,3,5.00,458,5.0,0.30%,52,2,Sweden,0,4,16,0,0
369,Stephen Kingsley,Swansea,22,LB,3,0.75,168,4.5,0.20%,29,2,Scotland,0,2,16,0,0
389,Ben Davies,Tottenham,24,LB,3,12.00,396,5.5,1.80%,90,2,Wales,0,2,17,1,0
390,Danny Rose,Tottenham,27,LB,3,28.00,848,6.5,0.60%,84,1,England,0,3,17,1,0
403,Jose Holebas,Watford,33,LB,3,2.00,345,5.0,0.60%,87,2,Greece,0,5,18,0,0
455,Aaron Cresswell,West+Ham,27,LB,3,12.00,380,5.0,1.30%,60,1,England,0,3,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.00,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1

In [29]:
players.age <= 25

0      False
1      False
2      False
3      False
4      False
       ...
460     True
461     True
462     True
463     True
464    False
Name: age, Length: 465, dtype: bool

In [30]:
players[(players.position == 'LB') & (players.age <= 25)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
29,Sead Kolasinac,Arsenal,24,LB,3,15.00,618,6.0,6.90%,0,2,Bosnia,1,2,1,1,0
54,Brad Smith,Bournemouth,23,LB,3,2.00,297,4.0,3.30%,4,4,Australia,0,2,2,0,0
112,Kenedy,Chelsea,21,LB,3,7.00,566,5.0,0.10%,3,3,Brazil,0,1,5,1,0
128,Jeffrey Schlupp,Crystal+Palace,24,LB,3,8.00,385,5.0,0.30%,47,4,Ghana,0,2,6,0,0
212,Ben Chilwell,Leicester+City,20,LB,3,2.50,288,4.5,0.80%,19,1,England,0,1,9,0,0
236,Alberto Moreno,Liverpool,25,LB,3,10.00,397,4.5,0.30%,8,2,Spain,0,3,10,1,0
281,Luke Shaw,Manchester+United,22,LB,3,20.00,947,5.0,0.40%,45,1,England,0,2,12,1,0
294,Paul Dummett,Newcastle+United,25,LB,3,3.50,177,4.5,1.00%,0,2,Wales,0,3,13,0,0
298,Massadio Haidara,Newcastle+United,24,LB,3,1.50,114,4.0,0.50%,0,2,France,0,2,13,0,0
328,Matt Targett,Southampton,21,LB,3,3.00,110,4.5,0.20%,12,1,England,0,1,14,0,0
354,Josh Tymon,Stoke+City,18,LB,3,1.00,120,4.5,0.10%,9,1,England,0,1,15,0,0
369,Stephen Kingsley,Swansea,22,LB,3,0.75,168,4.5,0.20%,29,2,Scotland,0,2,16,0,0
389,Ben Davies,Tottenham,24,LB,3,12.00,396,5.5,1.80%,90,2,Wales,0,2,17,1,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.00,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1

# Skill Challenge

In [31]:
# players with nationality = english =
english_players = players.nationality == 'England'
english_players

0      False
1      False
2      False
3       True
4      False
       ...
460    False
461    False
462     True
463     True
464    False
Name: nationality, Length: 465, dtype: bool

In [32]:
# market value is > 2 X Average market
players.market_value.sum()

5140.049999999999

In [33]:
players.market_value.shape[0]

465

In [34]:
average_mv = players.market_value.sum() / players.market_value.shape[0]
average_mv

11.053870967741934

In [35]:
more_than_avg = players.market_value > (2 * average_mv)

In [36]:
# have more than 400 views or a new signing
popular_xor = (players.page_views> 4000) ^ (players.new_signing >= 1)

In [37]:
result = (english_players & more_than_avg & popular_xor)

In [38]:
players.loc[result]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
256,John Stones,Manchester+City,23,CB,3,35.0,1078,5.5,2.30%,59,1,England,0,2,11,1,1
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

# 2D Indexing

In [39]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [40]:
chelsea_players = players.club == 'Chelsea'
chelsea_players

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: club, Length: 465, dtype: bool

In [41]:
Less_Than_23 = players.age <= 23
Less_Than_23

0      False
1      False
2      False
3      False
4      False
       ...
460     True
461     True
462     True
463     True
464    False
Name: age, Length: 465, dtype: bool

In [42]:
result = chelsea_players & Less_Than_23

In [43]:
players.loc[result]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
110,Michy Batshuayi,Chelsea,23,CF,1,25.0,1162,8.5,1.60%,48,2,Belgium,0,2,5,1,1
111,Kurt Zouma,Chelsea,22,CB,3,15.0,723,5.5,0.80%,15,2,France,0,2,5,1,0
112,Kenedy,Chelsea,21,LB,3,7.0,566,5.0,0.10%,3,3,Brazil,0,1,5,1,0
115,Tiemoue Bakayoko,Chelsea,22,DM,2,16.0,1011,5.0,1.60%,0,2,France,1,2,5,1,0

In [44]:
# indexing the column names from the result using the loc indexer
players.loc[result, ['name', 'market_value', 'nationality']]

                 name  market_value nationality
110   Michy Batshuayi          25.0     Belgium
111        Kurt Zouma          15.0      France
112            Kenedy           7.0      Brazil
115  Tiemoue Bakayoko          16.0      France

In [45]:
# Selecting all columns that start with 'p'
players.columns.str.startswith('p')

array([False, False, False,  True,  True, False,  True, False, False,
       False, False, False, False, False, False, False, False])

In [46]:
p_cols = players.columns.str.startswith('p')

In [47]:
players.loc[result, p_cols]

    position  position_cat  page_views
110       CF             1        1162
111       CB             3         723
112       LB             3         566
115       DM             2        1011

In [48]:
# [] Chaining

In [49]:
players.loc[result]['club']

110    Chelsea
111    Chelsea
112    Chelsea
115    Chelsea
Name: club, dtype: object

# Fancy Indexing : lookup()

In [50]:
players.loc[
    [0, 132],
    ('name', 'market_value')
]

               name  market_value
0    Alexis Sanchez          65.0
132  Connor Wickham           6.0

In [51]:
players.lookup(
    [0, 132],
    ['name', 'market_value']
)

<ipython-input-51-4ac5072e35ea>:1: FutureWarning: The 'lookup' method is deprecated and will be removed in a future version. You can use DataFrame.melt and DataFrame.loc as a substitute.
  players.lookup(

array(['Alexis Sanchez', 6.0], dtype=object)

# Sorting by index or column

In [52]:
players.sort_values(by = 'market_value', ascending = False)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
96,Eden Hazard,Chelsea,26,LW,1,75.00,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.00,7435,8.0,19.50%,115,2,France,0,2,12,1,1
0,Alexis Sanchez,Arsenal,28,LW,1,65.00,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.00,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.00,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,Joel Castro Pereira,Manchester+United,21,GK,4,0.10,395,4.0,1.00%,6,2,Portugal,0,1,12,1,0
113,Eduardo Carvalho,Chelsea,34,LW,1,0.05,467,5.0,0.10%,0,2,Portugal,0,6,5,1,1
30,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
192,Steve Mounie,Huddersfield,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0
195,Kasper Schmeichel,Leicester+City,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [53]:
players.set_index('name', inplace = True)

In [54]:
players.head()

,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
name,,,,,,,,,,,,,,,,
Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [55]:
players.sort_index(inplace = True)

In [56]:
players.sort_index(axis = 1)

,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,nationality,new_foreign,new_signing,page_views,position,position_cat,region
name,,,,,,,,,,,,,,,,
Aaron Cresswell,27,3,0,West+Ham,20,60,1.30%,5.0,12.0,England,0,0,380,LB,3,1
Aaron Lennon,30,4,0,Everton,7,22,0.20%,5.5,5.0,England,0,0,504,RW,1,1
Aaron Mooy,26,3,0,Huddersfield,8,0,2.50%,5.5,5.0,Australia,0,0,588,CM,2,4
Aaron Ramsey,26,3,1,Arsenal,1,56,5.10%,7.0,35.0,Wales,0,0,1040,CM,2,1
Abdoulaye Doucoure,24,2,0,Watford,18,38,0.00%,5.0,6.0,France,0,0,124,CM,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yohan Cabaye,31,4,0,Crystal+Palace,6,91,1.40%,5.5,15.0,France,0,0,456,CM,2,2
YounÃ¨s Kaboul,31,4,0,Watford,18,57,0.10%,4.5,2.5,France,0,1,263,CB,3,2
Ã‰tienne Capoue,29,4,0,Watford,18,131,8.00%,5.5,9.0,France,0,0,412,DM,2,2
Ã€ngel Rangel,34,6,0,Swansea,16,26,18.80%,4.0,1.0,Spain,0,0,137,RB,3,2
Åukasz FabiaÅ„ski,32,5,0,Swansea,16,116,6.20%,4.5,9.0,Poland,0,0,285,GK,4,2

In [57]:
players.reset_index(inplace = True)

In [58]:
players

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

# Sorting vs Reordering

In [59]:
# reordering of index rows and columns

In [60]:
players.reindex(
    index = [2, 1, 3, 4],
    columns = ['age', 'name', 'position']
)

   age                name position
2   26          Aaron Mooy       CM
1   30        Aaron Lennon       RW
3   26        Aaron Ramsey       CM
4   24  Abdoulaye Doucoure       CM

In [61]:
sorted_players_cols = sorted(players.columns)

In [62]:
players.reindex(index = [2, 1, 3, 0], columns = sorted_players_cols)

,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,name,nationality,new_foreign,new_signing,page_views,position,position_cat,region
2,26,3,0,Huddersfield,8,0,2.50%,5.5,5.0,Aaron Mooy,Australia,0,0,588,CM,2,4
1,30,4,0,Everton,7,22,0.20%,5.5,5.0,Aaron Lennon,England,0,0,504,RW,1,1
3,26,3,1,Arsenal,1,56,5.10%,7.0,35.0,Aaron Ramsey,Wales,0,0,1040,CM,2,1
0,27,3,0,West+Ham,20,60,1.30%,5.0,12.0,Aaron Cresswell,England,0,0,380,LB,3,1

In [63]:
players.columns.sort_values()

Index(['age', 'age_cat', 'big_club', 'club', 'club_id', 'fpl_points',
       'fpl_sel', 'fpl_value', 'market_value', 'name', 'nationality',
       'new_foreign', 'new_signing', 'page_views', 'position', 'position_cat',
       'region'],
      dtype='object')

# Skill Challenge

In [64]:
players.sort_values('age', ascending = True).name[:1]

53    Ben Woodburn
Name: name, dtype: object

In [65]:
players.sort_values('age', ascending = True)[:1]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
53,Ben Woodburn,Liverpool,17,LW,1,1.5,1241,4.5,0.10%,5,1,Wales,0,1,10,1,0

In [66]:
players.iloc[players.age.idxmin()]

name            Ben Woodburn
club               Liverpool
age                       17
position                  LW
position_cat               1
market_value             1.5
page_views              1241
fpl_value                4.5
fpl_sel                0.10%
fpl_points                 5
region                     1
nationality            Wales
new_foreign                0
age_cat                    1
club_id                   10
big_club                   1
new_signing                0
Name: 53, dtype: object

In [67]:
q2 = players.set_index('club').sort_values('club', ascending = True)

In [68]:
q2

,name,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
club,,,,,,,,,,,,,,,,
Arsenal,David Ospina,28,GK,4,7.0,544,5.0,0.20%,2,3,Colombia,0,4,1,1,0
Arsenal,Alexandre Lacazette,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0
Arsenal,Alexis Sanchez,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
Arsenal,Laurent Koscielny,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
Arsenal,Mesut Ozil,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West+Ham,Mark Noble,30,CM,2,7.0,425,5.5,0.10%,71,1,England,0,4,20,0,0
West+Ham,Michail Antonio,27,RW,1,18.0,1142,7.5,0.50%,132,1,England,0,3,20,0,0
West+Ham,Robert Snodgrass,29,RW,1,8.0,1210,6.0,6.50%,133,2,Scotland,0,4,20,0,0
West+Ham,Ashley Fletcher,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
West+Ham,Aaron Cresswell,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0

In [69]:
q2.sort_values('club', ascending = True).sort_values('market_value', ascending = False)

,name,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
club,,,,,,,,,,,,,,,,
Manchester+United,Paul Pogba,24,CM,2,75.00,7435,8.0,19.50%,115,2,France,0,2,12,1,1
Chelsea,Eden Hazard,26,LW,1,75.00,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
Arsenal,Alexis Sanchez,28,LW,1,65.00,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
Manchester+City,Sergio Aguero,29,CF,1,65.00,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
Manchester+City,Kevin De Bruyne,26,AM,1,65.00,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Manchester+United,Joel Castro Pereira,21,GK,4,0.10,395,4.0,1.00%,6,2,Portugal,0,1,12,1,0
Chelsea,Eduardo Carvalho,34,LW,1,0.05,467,5.0,0.10%,0,2,Portugal,0,6,5,1,1
Arsenal,Granit Xhaka,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
Huddersfield,Steve Mounie,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0
Leicester+City,Kasper Schmeichel,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [70]:
# Better approach
q2.sort_values(by = ['club', 'market_value'], ascending = [True, False])

,name,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
club,,,,,,,,,,,,,,,,
Arsenal,Alexis Sanchez,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
Arsenal,Mesut Ozil,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
Arsenal,Alexandre Lacazette,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0
Arsenal,Granit Xhaka,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
Arsenal,Granit Xhaka,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West+Ham,Edimilson Fernandes,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
West+Ham,Sam Byram,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
West+Ham,Darren Randolph,30,GK,4,2.5,459,4.5,0.40%,69,2,Ireland,0,4,20,0,0
West+Ham,James Collins,33,CB,3,2.0,187,4.5,0.90%,69,2,Wales,0,5,20,0,0
West+Ham,Ashley Fletcher,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1

# Identifying Duplicates

In [71]:
players.name

0         Aaron Cresswell
1            Aaron Lennon
2              Aaron Mooy
3            Aaron Ramsey
4      Abdoulaye Doucoure
              ...
460          Yohan Cabaye
461        YounÃ¨s Kaboul
462       Ã‰tienne Capoue
463         Ã€ngel Rangel
464    Åukasz FabiaÅ„ski
Name: name, Length: 465, dtype: object

In [72]:
players.name.unique().shape

(461,)

In [73]:
players.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Length: 465, dtype: bool

In [74]:
players[players.duplicated()]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
18,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
19,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
154,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0

In [75]:
# can specify the col without duplicate values
players.duplicated(subset = ['club', 'age', 'position', 'market_value'])

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Length: 465, dtype: bool

In [76]:
players[players.duplicated(subset = ['club', 'age', 'position', 'market_value'])]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
18,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
19,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
134,Fernando,Manchester+City,32,DM,2,18.0,338,4.5,0.40%,18,3,Brazil,0,5,11,1,0
154,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
252,Lascelles,Newcastle+United,27,CB,3,5.0,400,4.5,3.60%,0,1,England,0,3,13,0,0
281,Marcos Rojo,Manchester+United,27,CB,3,18.0,1063,5.5,0.10%,77,3,Argentina,0,3,12,1,0
399,Shane Duffy,Brighton+and+Hove,25,CB,3,5.0,243,4.5,0.60%,0,2,Ireland,0,3,3,0,0

In [77]:
players[players.duplicated(subset = ['club', 'age', 'position', 'market_value'], keep = 'first')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
18,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
19,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
134,Fernando,Manchester+City,32,DM,2,18.0,338,4.5,0.40%,18,3,Brazil,0,5,11,1,0
154,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
252,Lascelles,Newcastle+United,27,CB,3,5.0,400,4.5,3.60%,0,1,England,0,3,13,0,0
281,Marcos Rojo,Manchester+United,27,CB,3,18.0,1063,5.5,0.10%,77,3,Argentina,0,3,12,1,0
399,Shane Duffy,Brighton+and+Hove,25,CB,3,5.0,243,4.5,0.60%,0,2,Ireland,0,3,3,0,0

# Remove duplicates

In [78]:
players.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Length: 465, dtype: bool

In [79]:
players[players.duplicated()]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
18,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
19,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
154,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0

In [80]:
players.drop_duplicates(keep = 'first')

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [81]:
players.market_value.mean()

11.12564935064935

In [82]:
players.drop_duplicates(keep = 'first').market_value.mean()

11.026252723311547

# Removing dataframe rows

In [83]:
players[players.duplicated()]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
18,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
19,Alex Oxlade-Chamberlain,Arsenal,23,RM,2,22.0,1519,6.0,1.80%,83,1,England,0,2,1,1,0
154,Granit Xhaka,Arsenal,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0

In [84]:
players.drop(labels = 19, axis = 0)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [85]:
players.index

RangeIndex(start=0, stop=465, step=1)

In [86]:
players.drop(index = 19)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [87]:
players.drop(index = [10, 121, 130])

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [88]:
players.drop(labels = ['age', 'market_value'], axis = 'columns')

,name,club,position,position_cat,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,LB,3,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,RW,1,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,CM,2,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,CM,2,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,CM,2,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,CM,2,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,CB,3,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,DM,2,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,RB,3,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,GK,4,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

# Null Values in dataframe

In [99]:
players.age

0      27
1      30
2      26
3      26
4      24
       ..
460    31
461    31
462    29
463    34
464    32
Name: age, Length: 465, dtype: int64

In [100]:
ages = players.age

In [101]:
ages.isna()

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: age, Length: 465, dtype: bool

In [102]:
ages[ages.isna()]

Series([], Name: age, dtype: int64)

In [92]:
players.isna()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
461,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
462,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
463,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
464,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [93]:
# How many NA's are there in this dataframe
np.count_nonzero(players.isna())

4

In [94]:
# which are the na records
players.isna().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [95]:
players[players.isna().values]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
153,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
153,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
237,Kasper Schmeichel,Leicester+City,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0
415,Steve Mounie,Huddersfield,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0

In [96]:
players[players.isna().values].drop_duplicates()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
153,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
237,Kasper Schmeichel,Leicester+City,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0
415,Steve Mounie,Huddersfield,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0

# Dropping and Filling dataframe NAs

In [108]:
players.fillna('nulls replaced')

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [107]:
players.fillna('nulls replaced').loc[[153, 237]]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
153,Granit Xhaka,Arsenal,24,nulls replaced,2,nulls replaced,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
237,Kasper Schmeichel,Leicester+City,30,GK,4,nulls replaced,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [111]:
players.fillna(
    {
        'market_value' : 100,
        'position' : 'RM'
    }
).loc[[153, 237]]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
153,Granit Xhaka,Arsenal,24,RM,2,100.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
237,Kasper Schmeichel,Leicester+City,30,GK,4,100.0,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [112]:
players.fillna(
    {
        'market_value' : players.market_value.mean(),
        'position' : 'RM'
    }
).loc[[153, 237]]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
153,Granit Xhaka,Arsenal,24,RM,2,11.125649,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
237,Kasper Schmeichel,Leicester+City,30,GK,4,11.125649,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

In [115]:
# drop nulls
players.dropna()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,5.0,504,5.5,0.20%,22,1,England,0,4,7,0,0
2,Aaron Mooy,Huddersfield,26,CM,2,5.0,588,5.5,2.50%,0,4,Australia,0,3,8,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,35.0,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,6.0,124,5.0,0.00%,38,2,France,0,2,18,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,15.0,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,2.5,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,9.0,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,1.0,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,9.0,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

# Skill Challenge

In [116]:
# From our players dataframe remove the rows labelled 2, 10, 21 and the market value cols. Assing the dataframe to df2

In [131]:
df2 = players.drop(labels = ['market_value'], axis = 1).drop(index = [2, 10, 21])

In [132]:
df2

,name,club,age,position,position_cat,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,504,5.5,0.20%,22,1,England,0,4,7,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,124,5.0,0.00%,38,2,France,0,2,18,0,0
5,Adam Federici,Bournemouth,32,GK,4,126,4.0,1.50%,8,4,Australia,0,5,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [135]:
df2[df2.nationality.isna()]

Empty DataFrame
Columns: [name, club, age, position, position_cat, page_views, fpl_value, fpl_sel, fpl_points, region, nationality, new_foreign, age_cat, club_id, big_club, new_signing]
Index: []

In [144]:
df2.nationality.unique().size

61

In [145]:
df2.drop_duplicates(
    subset = ['age', 'club', 'position'],
    keep = 'first'
)

,name,club,age,position,position_cat,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Aaron Cresswell,West+Ham,27,LB,3,380,5.0,1.30%,60,1,England,0,3,20,0,0
1,Aaron Lennon,Everton,30,RW,1,504,5.5,0.20%,22,1,England,0,4,7,0,0
3,Aaron Ramsey,Arsenal,26,CM,2,1040,7.0,5.10%,56,1,Wales,0,3,1,1,0
4,Abdoulaye Doucoure,Watford,24,CM,2,124,5.0,0.00%,38,2,France,0,2,18,0,0
5,Adam Federici,Bournemouth,32,GK,4,126,4.0,1.50%,8,4,Australia,0,5,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Yohan Cabaye,Crystal+Palace,31,CM,2,456,5.5,1.40%,91,2,France,0,4,6,0,0
461,YounÃ¨s Kaboul,Watford,31,CB,3,263,4.5,0.10%,57,2,France,0,4,18,0,1
462,Ã‰tienne Capoue,Watford,29,DM,2,412,5.5,8.00%,131,2,France,0,4,18,0,0
463,Ã€ngel Rangel,Swansea,34,RB,3,137,4.0,18.80%,26,2,Spain,0,6,16,0,0
464,Åukasz FabiaÅ„ski,Swansea,32,GK,4,285,4.5,6.20%,116,2,Poland,0,5,16,0,0

In [146]:
df2.drop_duplicates(
    subset = ['age', 'club', 'position'],
    keep = 'first'
).loc[:, ['age', 'position']]

     age position
0     27       LB
1     30       RW
3     26       CM
4     24       CM
5     32       GK
..   ...      ...
460   31       CM
461   31       CB
462   29       DM
463   34       RB
464   32       GK

[433 rows x 2 columns]